export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const INCREMENT_DAY = 'INCREMENT_DAY';
export const DECREMENT_DAY = 'DECREMENT_DAY';
export const CALENDAR_SELECTION = 'CALENDAR_SELECTION';
export const DATE_RANGE_START_DATE_SELECTED = 'DATE_RANGE_START_DATE_SELECTED';
export const DATE_RANGE_END_DATE_SELECTED = 'DATE_RANGE_END_DATE_SELECTED';
